### ISSUE TITLE
OpenAI's model gpt-4-vision-preview has been deprecated

### ISSUE THREAD

**Issue by ultragolden** [HosakaKeigo/FileMaker-OpenAI-Playground#1]
The model used to demo OpenAI Vision, gpt-4-vision-preview, has been deprecated by OpenAI.  There are several models which do support Vision such as gpt-4-0125-preview, but they don't support analyzing an image via a URL.  The image can be "sent" to the model by encoding it as Base64 and modifying the payload being sent to the model, but this requires code changes to the Filemaker-OpenAI-Playground.  Other features of the Playground appear to function as expected.

**Comment by HosakaKeigo** [comment]
@ultragolden 
Thanks. I made changes to use gpt-4o for both text and vision generations.
- https://github.com/HosakaKeigo/FileMaker-OpenAI-Playground/commit/8bb9b0dffa87566e98a3d89baa619998ee112815
